DROP TABLE IF EXISTS equipo4.TWILIO_ACCOUNT;
DROP TABLE IF EXISTS equipo4.USUARIO;
CREATE TABLE equipo4.TWILIO_ACCOUNT (ID INT IDENTITY PRIMARY KEY,account_sid VARCHAR(255),auth_token VARCHAR(255),phone_number VARCHAR(12));
CREATE TABLE equipo4.USUARIO (ID INT IDENTITY PRIMARY KEY,USERNAME VARCHAR(30),PASSWORD VARCHAR(255),EMAIL VARCHAR(30),PHONE_NUMBER VARCHAR(9));